### ISSUE TITLE
Replace k256 library with rust-secp256k1

### ISSUE THREAD

**Issue by lescuer97** [thesimplekid/cashu-crab#35]
Hi! I was having a look around the code and notice the library is using k256 instead of the [rust-secp256k1](https://github.com/rust-bitcoin/rust-secp256k1) library. k256 is not cryptographic audited compared to rust-secp256k1 which is probably the most audited crypto library out there. 

I was looking to work on a cashu library and found this package. do you think this would be a good change? 
I would probably be interested in doing the change.

**Comment by thesimplekid** [comment]
Hi,

Thank you for taking a look. Ideally we would use rust-secp256k1 however it cannot compile to wasm, and I wasn't this library to be as cross platform as possible. There is an open issue for wasm support in rust-secp256k1 but it may take some time as it's not an issue with the lib itself it's a wider c binding issue. I'll put in a link to the issue later when I'm not on mobile.

**Comment by thesimplekid** [comment]
Issue on rust-secp256k1:

<https://github.com/rust-bitcoin/rust-secp256k1/issues/485>


Wider rust issue:

<https://github.com/rustwasm/team/issues/291>

**Comment by yukibtc** [comment]
I agree, I think we should use `secp256k1` instead of `k256` for the same reason you said. That's one of the things I started doing in my fork :)

---

`rust-secp256k1` can be compiled to WASM. If you are on macOS you need to do this:

```bash
brew install llvm
LLVM_PATH=$(brew --prefix llvm)
AR="${LLVM_PATH}/bin/llvm-ar" CC="${LLVM_PATH}/bin/clang" cargo build --target wasm32-unknown-unknown
```

On Linux it works without having to do anything (at least on debian).

**Comment by yukibtc** [comment]
I can take this issue if you're not already working on it, so I can get more familiar with the library :)

**Comment by thesimplekid** [comment]
> I can take this issue if you're not already working on it, so I can get more familiar with the library 

I haven't started so that's great, thanks

**Comment by thesimplekid** [comment]
> That's one of the things I started doing in my fork 

Definitely open an issue or shoot me a message with any other suggestions
