### ISSUE TITLE
Simplify mint after NUT-06 update (`amount` deprecation)

### ISSUE THREAD

**Issue by callebtc** [thesimplekid/cashu-crab#4]
Hey, I was glancing over the code and saw that after the [NUT-06](https://github.com/cashubtc/nuts/pull/34) update [here](https://github.com/thesimplekid/cashu-crab/commit/e8303fcc8c545111ddfbeb72739d5bd757123157), you might have left some idiosyncrasies from earlier times in the code:

https://github.com/thesimplekid/cashu-crab/blob/b287c87df0e6d87468d7dfa6d0a48e014967834f/src/mint.rs#L133

Since the mint does not know anything about "first" and "second" promises (blind signatures) anymore, you can treat these as one big slice and don't have to separate them anymore. Instead, the wallet now has to figure out which of the `promises` it received it wants to keep and which to send on. I am guessing, this is what your code does here:

https://github.com/thesimplekid/cashu-crab/blob/b287c87df0e6d87468d7dfa6d0a48e014967834f/src/wallet.rs#L110C21-L110C29

Keep up the insane work! Cheers!

**Comment by thesimplekid** [comment]
Hey, 

Thanks for taking a look, I kept that in so the mint could handle requests from wallets that have not updated and those that did. But you're right best to remove it now. 

Yes, I updated the wallet to deprecate the amount field and figure out the promises.  

https://github.com/thesimplekid/cashu-crab/blob/b287c87df0e6d87468d7dfa6d0a48e014967834f/src/mint.rs#L115-L126

**Comment by thesimplekid** [comment]
150ba204019cc92b7310d1abb230793a679e97ad
