### ISSUE TITLE
Refactor wallet

### ISSUE THREAD

**Issue by ngutech21** [thesimplekid/cashu-crab#43]
The wallet-module in the cashu-sdk crate has several issues:

- All methods are implemented twice: once for the blocking client and once for the non-blocking client. This could make future code upgrades challenging.
- The wallet-struct is not testable with pure unittests, because it relies on a specific http-client. Mocking the client is hard, therefore this struct could only be tested with integrationstests.

Solution:
## Introduce a trait for the client

```rust
#[async_trait(?Send)]
pub trait Client {
async fn get_keys(&self) -> Result<Keys, Error> 
...
}
```

## Use a generic argument in the wallet with Client as the trait-bound
```rust
#[derive(Clone, Debug)]
pub struct Wallet<C: Client> {
    pub client: C,
    pub mint_keys: Keys,
    pub balance: Amount,
}
```  

This way we can have multiple implementations for clients (e.g. use reqwest for the regular desktop wallets and gloo-net for wasm clients)  and get rid of the duplicated code for the logic in the wallet module 
For unittests there can can also be an mock implementation using automock or a manual created one. 

The refactoring would also fix this issue: #41 

This is how I structured the wallet in my cashu-implementation https://github.com/ngutech21/moksha/blob/master/moksha-wallet/src/wallet.rs

**Comment by thesimplekid** [comment]
Thanks for pointing me in this direction this looks like a much better way to do it, as I agree the current way needs to be improved. I'll work in implementing this hopefully this weekend.
