### ISSUE TITLE
Use thiserror for implementing custom error types

### ISSUE THREAD

**Issue by ngutech21** [thesimplekid/cashu-crab#44]
Instead of implementing the From-trait manually, I would recommend using thiserror crate https://docs.rs/thiserror/latest/thiserror/
This would get rid of most of the boilerplate code in the error types.

**Comment by thesimplekid** [comment]
Initially I did this to avoid a dependency, however I think you're right that using thiserror makes sense to avoid the boilerplate. So I will change this.

**Comment by thesimplekid** [comment]
Complete in:

61cfd5d53c812865202d9ebc4cefee9d08f133fb
99dd07ed0b5551d67fb4b3c19f7fabf3704dee51
660c767df45fd85ea02d46b7b414a799b9dc3858
f85df7316f9e6e774da7982b55c1b9a11f7422b3
