### ISSUE TITLE
Decode token: Base64Error(InvalidPadding)

### ISSUE THREAD

**Issue by DanielUhlik** [thesimplekid/cashu-crab#48]
Decoding tokens where mint url have path cause error `Base64Error(InvalidPadding)`

Code to reproduce:
```rust
use cashu_sdk::nuts::nut00::wallet::Token;

fn main() {
    let token = Token::from_str("cashuAeyJ0b2tlbiI6W3sicHJvb2ZzIjpbeyJpZCI6IjBOSTNUVUFzMVNmeSIsImFtb3VudCI6MSwic2VjcmV0IjoiVE92cGVmZGxSZ0EzdlhMN05pM2MvRE1oY29URXNQdnV4eFc0Rys2dXVycz0iLCJDIjoiMDNiZThmMzQwOTMxYTI4ZTlkMGRmNGFmMWQwMWY1ZTcxNTFkMmQ1M2RiN2Y0ZDAyMWQzZGUwZmRiMDNjZGY4ZTlkIn1dLCJtaW50IjoiaHR0cHM6Ly9sZWdlbmQubG5iaXRzLmNvbS9jYXNodS9hcGkvdjEvNGdyOVhjbXozWEVrVU53aUJpUUdvQyJ9XX0");
    println!("Mint url: {}", token.unwrap().token[0].mint);
}
```

**Comment by DanielUhlik** [comment]
It does not matter where token is generated, I tried tokens generated with this lib and generated using other wallets. I only think that url is problem because https://8333.space:8333 is working Ok, this token (https://legend.lnbits.com/cashu/api/v1/4gr9Xcmz3XEkUNwiBiQGoC) or with url https://localhost:5000/cashu does not work

**Comment by thesimplekid** [comment]
Is it possible you copied it without the `=` at the end?

```rust
        let token = Token::from_str("cashuAeyJ0b2tlbiI6W3sicHJvb2ZzIjpbeyJpZCI6IjBOSTNUVUFzMVNmeSIsImFtb3VudCI6MSwic2VjcmV0IjoiVE92cGVmZGxSZ0EzdlhMN05pM2MvRE1oY29URXNQdnV4eFc0Rys2dXVycz0iLCJDIjoiMDNiZThmMzQwOTMxYTI4ZTlkMGRmNGFmMWQwMWY1ZTcxNTFkMmQ1M2RiN2Y0ZDAyMWQzZGUwZmRiMDNjZGY4ZTlkIn1dLCJtaW50IjoiaHR0cHM6Ly9sZWdlbmQubG5iaXRzLmNvbS9jYXNodS9hcGkvdjEvNGdyOVhjbXozWEVrVU53aUJpUUdvQyJ9XX0=").unwrap();

```
![image](https://github.com/thesimplekid/cashu-crab/assets/8606367/806ff5c5-8ebf-46ea-8d0d-11bb40d3a850)

By adding an `=` to the end the above works for me without an error.

**Comment by thesimplekid** [comment]
Though it looks like nutshell handles it with or without the ending `=` so i should do the same.

**Comment by thesimplekid** [comment]
The issue was that this lib was enforcing proper padding of the base64 token string. In af23f89d96e9d0b02ad62f9402ee63b388b4a8a3 I've fixed this so tokens with or without padding are decoded. However, This lib will encode them with padding. 

Going to close this since i believe it is fixed. Let me know if you still have issues.
