### ISSUE TITLE
Bug: Same token

### ISSUE THREAD

**Issue by shanelau** [thesimplekid/cashu-crab#6]
When I execute the code twice or more, it is possible to generate the same token,  it should generate a completely different token.

Sometimes , even though the balance is sufficient, the call will return an error: Token already spent.

## My Code
```
        let  r6 = api::send(1, "https://8333.space:3338/".to_string());
        let  r7 = api::send(1, "https://8333.space:3338/".to_string());
        let  r8 = api::send(1, "https://8333.space:3338/".to_string());
```

## result

```
r6 :Ok(CashuTransaction(CashuTransaction { id: Some("991b5fcbe03fb8ddf50fcb94308e7579ecc82b589f2b6425cd0b0f510751ce98"), status: Pending(Send), time: 1692633929, amount: 1, mint: "https://8333.space:3338/", token: "cashuAeyJ0b2tlbiI6W3sibWludCI6Imh0dHBzOi8vODMzMy5zcGFjZTozMzM4IiwicHJvb2ZzIjpbXX1dLCJtZW1vIjpudWxsfQ==", from: None }))
r7 :Ok(CashuTransaction(CashuTransaction { id: Some("991b5fcbe03fb8ddf50fcb94308e7579ecc82b589f2b6425cd0b0f510751ce98"), status: Pending(Send), time: 1692633931, amount: 1, mint: "https://8333.space:3338/", token: "cashuAeyJ0b2tlbiI6W3sibWludCI6Imh0dHBzOi8vODMzMy5zcGFjZTozMzM4IiwicHJvb2ZzIjpbXX1dLCJtZW1vIjpudWxsfQ==", from: None }))
```

**Comment by shanelau** [comment]
Token is wrong:
cashuAeyJ0b2tlbiI6W3sibWludCI6Imh0dHBzOi8vODMzMy5zcGFjZTozMzM4IiwicHJvb2ZzIjpbXX1dLCJtZW1vIjpudWxsfQ==

Verify it : https://wallet.cashu.me/

**Comment by thesimplekid** [comment]
> Token is wrong:
cashuAeyJ0b2tlbiI6W3sibWludCI6Imh0dHBzOi8vODMzMy5zcGFjZTozMzM4IiwicHJvb2ZzIjpbXX1dLCJtZW1vIjpudWxsfQ==

When i decode this with this library there are no proofs in it. Do you know if you created this without any proofs as there is no check for that (there should be)?

**Comment by thesimplekid** [comment]
> When i decode this with this library there are no proofs in it. Do you know if you created this without any proofs as there is no check for that (there should be)?

added a check 4a7ea24be00c67c7d49f7d07772cc93ee4723158
